# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '微博分类',
                'verbose_name_plural': '微博分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='时间')),
                ('comment_type', models.IntegerField(choices=[(0, '评论'), (1, '点赞')], default=0, verbose_name='类型')),
                ('comment', models.CharField(max_length=140)),
                ('p_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='WeiboContent.Comment')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='话题名字')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用户名称')),
                ('brief', models.CharField(blank=True, max_length=140, null=True, verbose_name='简介')),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('head_img', models.ImageField(upload_to='', verbose_name='头像')),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='WeiboContent.UserProfile')),
                ('tags', models.ManyToManyField(to='WeiboContent.Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登录账号')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_type', models.IntegerField(choices=[(0, '原创'), (1, '转发'), (2, '收藏')], default=0, verbose_name='微博类型')),
                ('text', models.CharField(max_length=140, verbose_name='微博内容')),
                ('pictures_link_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='照片路径')),
                ('video_link_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='视频路径')),
                ('perm', models.IntegerField(choices=[(0, '公开'), (1, '自己可见'), (2, '朋友可见')], default=0, verbose_name='可见度')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('forward_or_collect_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_or_collects', to='WeiboContent.Weibo', verbose_name='关联微博')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeiboContent.UserProfile', verbose_name='用户')),
            ],
            options={
                'verbose_name': '所有微博内容',
                'verbose_name_plural': '所有微博内容',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='to_weibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeiboContent.Weibo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WeiboContent.UserProfile'),
        ),
    ]
