# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboContent', '0002_auto_20160922_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(upload_to='./static/user/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='text',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='微博内容'),
        ),
    ]
